# Generated by Django 5.1.2 on 2024-12-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_user_remove_profile_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
