# Generated by Django 5.1.2 on 2024-12-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profile_picture_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
