# Generated by Django 5.1.2 on 2024-12-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0002_remove_eventregistration_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='user',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
