# Generated by Django 5.1.2 on 2024-12-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20241208_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
